version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mediahub
      POSTGRES_PASSWORD: mediahub
      POSTGRES_DB: mediahub
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mediahub"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./apps/api
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports: ["8080:8080"]
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://mediahub:mediahub@db:5432/mediahub
      REDIS_URL: redis://redis:6379

  worker:
    build: ./apps/api
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://mediahub:mediahub@db:5432/mediahub
      REDIS_URL: redis://redis:6379
    command: npm run worker

volumes:
  postgres_data:
  redis_data:
