version: '3.8'
services:
  api:
    build: ../apps/api
    env_file: ../.env
    ports:
      - '8080:8080'
    depends_on:
      - redis
    command: npm run dev
  web:
    build: ../apps/web
    env_file: ../.env
    ports:
      - '3000:3000'
    command: npm run dev
  worker:
    build: ../apps/worker
    env_file: ../.env
    depends_on:
      - redis
    command: npm run dev
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
  caddy:
    image: caddy:2-alpine
    ports:
      - '80:80'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - api
      - web
